@FerreteríaWeb_Backend_HostAddress = http://localhost:5000

POST {{FerreteríaWeb_Backend_HostAddress}}/api/provider
Content-Type: application/json

{
    "rfc": "ABCD123456XYQ",
    "name": "Proveedor Ejemplo",
    "phone": "2284756321",
    "email": "proveedor@gmail.com",
    "address": "Calle Falsa 123, Ciudad, País"
}
###

GET {{FerreteríaWeb_Backend_HostAddress}}/api/provider/2
Accept: application/json
###

PUT {{FerreteríaWeb_Backend_HostAddress}}/api/provider/2
Content-Type: application/json

{
    "rfc": "ABCD123456XYQ",
    "name": "Proveedor Ejemplo actualizado",
    "phone": "2284756321",
    "email": "proveedor@gmail.com",
    "phone": "2298765432",
    "address": "Calle Falsa 123, Ciudad, País",s
    "active": false
}

###
POST {{FerreteríaWeb_Backend_HostAddress}}/api/employees
Content-Type: application/json

{
    "name": "a",
    "lastname": "q",
    "secondlastname": "q",
    "email": "admin@gmail.com",
    "phone": "2284756321",
    "birthdate": "1990-01-01T00:00:00",
    "gender": "M",
    "city": "Ciudad",
    "address": "Calle Falsa 123",
    "postalcode": "12345",
    "password": "contrasenaSegura1*",
    "confirmPassword": "contrasenaSegura1*"
}
###

GET {{FerreteríaWeb_Backend_HostAddress}}/api/provider
Accept: application/json
###

PATCH  {{FerreteríaWeb_Backend_HostAddress}}/api/provider/1/state
###

GET {{FerreteríaWeb_Backend_HostAddress}}/api/products?s=la
Accept: application/json
###

POST {{FerreteríaWeb_Backend_HostAddress}}/api/sale
Content-Type: application/json

{
    "paymentMethod": "cash",
    "employeeId": 2,
    "saleDetails": [
        {
            "productId": 1,
            "productQuantity": 5
        }
    ]
}

###
GET {{FerreteríaWeb_Backend_HostAddress}}/api/products/1
Accept: application/json
###

POST {{FerreteríaWeb_Backend_HostAddress}}/api/purchase
Content-Type: application/json

{
    "providerId": 2,
    "employeeId": 1,
    "products": [
        {
            "id": 1,
            "quantity": 10
        }
    ]
}
###